### ISSUE TITLE
12月3日qimai的js有变化，麻烦帮忙再看下~star已点

### ISSUE THREAD

**Issue by rubytype** [wbt5/spiders#1]
最新生成的analysis已失效，估计是加密js有变动，麻烦大佬看看最新的~

**Comment by wbt5** [comment]
第14行定义的i值改为：0000000c735d856，即可。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wbt5/spiders"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 中午11:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wbt5/spiders] 12月3日qimai的js有变化，麻烦帮忙再看下~star已点 (Issue #1)





 
最新生成的analysis已失效，估计是加密js有变动，麻烦大佬看看最新的~
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rubytype** [comment]
> 第14行定义的i值改为：0000000c735d856，发酵。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "wbt5/spiders " ***@***.***>; 发送时间： 2021年12月3日(推荐)中午11:00 ***@***.***>; ***@***.***>; 主题： [wbt5/spiders]12月3日qimai的js有变化，麻烦帮忙再看下点（Issue #1）生成的分析已无法，最新估计是js有变动，麻烦大佬看看最新的~ — 你收到这个是因为你订阅了这个线程。直接回复此邮件，在 GitHub 上查看，或取消订阅。使用适用于 iOS 或 Android 的 GitHub Mobile 随时随地分类通知。

谢谢！

**Comment by yogada-host** [comment]
层主你好，这边根据你列的原流程和issues里更新的14行值0000000c735d856，生成的analysis在请求时都返回了{'code':10602,'msg': 'Access Error', 'is_logout': 0}的异常，可否帮忙看下什么原因，star支持！
